"""Add trip_stations models

Revision ID: 349b02c05c8d
Revises: b2ca49628229
Create Date: 2025-07-07 15:57:18.047137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349b02c05c8d'
down_revision: Union[str, None] = 'b2ca49628229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'station_id', 'day_number', name='uq_trip_station_day')
    )
    op.create_index(op.f('ix_trip_stations_id'), 'trip_stations', ['id'], unique=False)
    op.add_column('stations', sa.Column('station_name_de', sa.String(length=100), nullable=False))
    op.alter_column('stations', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('stations_trip_id_fkey'), 'stations', type_='foreignkey')
    op.drop_column('stations', 'day_number')
    op.drop_column('stations', 'trip_id')
    op.add_column('users', sa.Column('language_preference', sa.String(length=5), nullable=False,
                                     server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_preference')
    op.add_column('stations', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stations', sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stations_trip_id_fkey'), 'stations', 'trips', ['trip_id'], ['id'])
    op.alter_column('stations', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('stations', 'station_name_de')
    op.drop_index(op.f('ix_trip_stations_id'), table_name='trip_stations')
    op.drop_table('trip_stations')
    # ### end Alembic commands ###
